export {default as Demo01} from './demo01'
export {default as Demo02} from './demo02'
export {default as Demo03} from './demo03'
export {default as Demo04} from './demo04'
export {default as Demo05} from './demo05'